### ISSUE TITLE
Please update the "mobileraker_pro"

### ISSUE THREAD

**Issue by parkkh12** [Clon1998/mobileraker_pro_pub#1]
### Problem Description
I'm trying to build an app but it says there's no spoolman file.

### Proposed Solution
Update File

### Alternatives Considered
If you've thought of any alternative solutions or features, please briefly describe them here.

### Additional Context
![image](https://github.com/Clon1998/mobileraker/assets/73895939/fff7e3cd-83aa-459b-ba4b-c1caf97720e1)

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [x] Provided a clear description of the problem you're facing.
- [x] Clearly outlined the proposed solution or feature.
- [ ] Mentioned any alternative solutions or ideas you've considered.
- [ ] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment]
Moved to correct repo,

I will update this repo to reflect the latest "Pro" classes.
